### ISSUE TITLE
ownership of `TaskGroup`

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/task-group#2]
Ideally the group would be borrowed. But we can't support that yet. Instead we should make it so the group needs to be returned from the closure, and the group is !Clone.

**Comment by Seeker14491** [comment]
Looks like this was implemented in commit https://github.com/yoshuawuyts/async-task-group/commit/b6656f7953ac273b18025980e40ef0b8e1d7519d.

**Comment by yoshuawuyts** [comment]
Oh yeah, good catch. That's right, we can close this.
